name: Build SCBViewer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build with Makefile (Linux)
      run: make

    - name: Create artifact (Linux)
      uses: actions/upload-artifact@v3
      with:
        name: scbviewer-linux
        path: ./scb2obj  # Adjust the binary name/path if different

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install MinGW
      run: choco install mingw

    - name: Set up MinGW
      run: |
        echo "::add-path::C:/Program Files/mingw-w64/bin"
        echo "::set-env name=CC::gcc"

    - name: Build with Makefile (Windows)
      run: mingw32-make.exe

    - name: Create artifact (Windows)
      uses: actions/upload-artifact@v3
      with:
        name: scbviewer-windows
        path: ./scb2obj.exe  # Adjust the binary name/path if different

  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download Linux build artifact
      uses: actions/download-artifact@v3
      with:
        name: scbviewer-linux

    - name: Download Windows build artifact
      uses: actions/download-artifact@v3
      with:
        name: scbviewer-windows

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          scbviewer-linux/scb2obj
          scbviewer-windows/scb2obj.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
