name: Build SCBViewer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [created]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build with Makefile (Linux)
      run: make

    - name: Upload artifact (Linux)
      uses: actions/upload-artifact@v3
      with:
        name: scbviewer-linux
        path: ./scb2obj

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install MinGW
      run: choco install mingw

    - name: Build with Makefile (Windows)
      run: mingw32-make.exe

    - name: Upload artifact (Windows)
      uses: actions/upload-artifact@v3
      with:
        name: scbviewer-windows
        path: ./scb2obj.exe

  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
    - uses: actions/checkout@v4

    - name: Download Linux build artifact
      uses: actions/download-artifact@v3
      with:
        name: scbviewer-linux

    - name: Download Windows build artifact
      uses: actions/download-artifact@v3
      with:
        name: scbviewer-windows

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          scbviewer-linux/scb2obj
          scbviewer-windows/scb2obj.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
